---
title: "EP11"
author: ""
date: "2024-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## EP11 


```{r}
library(dplyr)
```

```{r}
set.seed(20761)
```




```{r}
# Leer los datos
nombre_archivo <- "EP09 Datos.csv"
carpeta <- "/home/seba/Documentos/ejercicios_R/EI/estadistica_inferencial_grupo5/EP10"
ruta <- file.path(carpeta, nombre_archivo)
datos <- read.csv2(ruta, stringsAsFactors = TRUE)

```


```{r}
# Leer los datos

nombre_archivo <- "EP09 Datos.csv"
carpeta <- "C:/Users/josef/Downloads"
ruta <- file.path(carpeta, nombre_archivo)
datos <- read.csv2(ruta, stringsAsFactors = TRUE)
```


```{r}
# Calcular el IMC
datos$IMC <- datos$Weight / ((datos$Height*1/100)^2)


# Crear la variable dicotómica EN (estado nutricional)
datos$EN <- ifelse(datos$IMC >= 23.2, 1, 0)

# Separar personas con "Sobrepeso" y "No sobrepeso"
personas_sobrepeso <- subset(datos, EN == 1)
personas_no_sobrepeso <- subset(datos, EN == 0)

# Seleccionar 75 mujeres de cada grupo (75 "Sobrepeso" y 75 "No sobrepeso")
muestra_sobrepeso <- personas_sobrepeso[sample(nrow(personas_sobrepeso), 50, replace = FALSE), ]
muestra_no_sobrepeso <- personas_no_sobrepeso[sample(nrow(personas_no_sobrepeso), 50, replace = FALSE), ]


# Dividir la muestra en dos conjuntos
# 100 personas (50 con EN "Sobrepeso" y 50 con EN "No sobrepeso") para el modelo RLO
entrenamiento <- rbind(
  muestra_sobrepeso[1:50, ],
  muestra_no_sobrepeso[1:50, ]
)

# 50 personas (25 con EN "Sobrepeso" y 25 con EN "No sobrepeso") para la evaluación
evaluacion <- rbind(
  muestra_sobrepeso[51:75, ],
  muestra_no_sobrepeso[51:75, ]
)

```


```{r}
library(leaps)

# Especifica la fórmula para la selección de variables
# Incluye todas las variables originales excepto IMC y EN
formula <- Weight ~ . - IMC - EN

# Realiza la búsqueda exhaustiva con leaps
modelos <- regsubsets(formula, data = entrenamiento, nbest = 1, nvmax = 8, method = "exhaustive")

# Resumen de los modelos ajustados
summary_modelos <- summary(modelos)
print(summary_modelos)

plot(modelos)

#1.Chest.depth
#2.Waist.Girth
#3.Navel.Girth
#4.Thigh.Girth
#5.Forearm.Girth
#6.Calf.Maximum.Girth
#7.Ankle.Minimum.Girth
#8.Age
#9.Height


```




